//! Specialized LLMs for the cue feature.

pub mod answer;
pub mod recap;
pub mod suggest;

pub use answer::AnswerLlm;
pub use recap::RecapLlm;
pub use suggest::WhatToAnswerLlm;

use serde::{Deserialize, Serialize};

/// A cue response generated by one of the specialized LLMs.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CueResponse {
    pub id: String,
    pub kind: String,
    pub text: String,
    pub ts_ms: u64,
    pub source_session_id: String,
    pub source_text: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cost_cents: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub balance_cents_after: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub provider: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub input_tokens: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub output_tokens: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cost_label: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub artifact_type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub artifact_body: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub artifact_confidence: Option<f32>,
}

impl CueResponse {
    pub fn new(kind: &str, text: String, session_id: &str, source_text: Option<String>) -> Self {
        Self {
            id: uuid::Uuid::new_v4().to_string(),
            kind: kind.to_string(),
            text,
            ts_ms: std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap_or_default()
                .as_millis() as u64,
            source_session_id: session_id.to_string(),
            source_text,
            cost_cents: None,
            balance_cents_after: None,
            provider: None,
            model: None,
            input_tokens: None,
            output_tokens: None,
            cost_label: None,
            artifact_type: None,
            artifact_body: None,
            artifact_confidence: None,
        }
    }

    pub fn with_cost_metadata(mut self, cost: Option<&cue_llm::LlmCostMetadata>) -> Self {
        if let Some(cost) = cost {
            self.cost_cents = Some(cost.cost_cents);
            self.balance_cents_after = cost.balance_cents_after;
            self.provider = Some(cost.provider.clone());
            self.model = Some(cost.model.clone());
            self.input_tokens = Some(cost.input_tokens);
            self.output_tokens = Some(cost.output_tokens);
        }
        self
    }

    pub fn with_llm_metadata(
        mut self,
        cost: Option<&cue_llm::LlmCostMetadata>,
        cost_label: Option<&str>,
        artifact: Option<&cue_llm::LlmArtifactMetadata>,
    ) -> Self {
        self = self.with_cost_metadata(cost);
        self.cost_label = cost_label.map(ToOwned::to_owned);
        if let Some(artifact) = artifact {
            self.artifact_type = Some(artifact.artifact_type.clone());
            self.artifact_body = Some(artifact.body.clone());
            self.artifact_confidence = artifact.confidence;
        }
        self
    }
}

/// Detect if text ends with a question.
pub fn ends_with_question(text: &str) -> bool {
    text.trim().ends_with('?')
}
