//! Specialized LLMs for the cue feature.

mod answer;
mod recap;
mod suggest;

pub use answer::AnswerLlm;
pub use recap::RecapLlm;
pub use suggest::WhatToAnswerLlm;

use serde::{Deserialize, Serialize};

/// A cue response generated by one of the specialized LLMs.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CueResponse {
    pub id: String,
    pub kind: String,
    pub text: String,
    pub ts_ms: u64,
    pub source_session_id: String,
    pub source_text: Option<String>,
}

impl CueResponse {
    pub fn new(kind: &str, text: String, session_id: &str, source_text: Option<String>) -> Self {
        Self {
            id: uuid::Uuid::new_v4().to_string(),
            kind: kind.to_string(),
            text,
            ts_ms: std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap_or_default()
                .as_millis() as u64,
            source_session_id: session_id.to_string(),
            source_text,
        }
    }
}

/// Detect if text ends with a question.
pub fn ends_with_question(text: &str) -> bool {
    text.trim().ends_with('?')
}
