[package]
name = "cue-core"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
dirs.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true

[lints.clippy]
derivable_impls = "allow"
large_enum_variant = "allow"
should_implement_trait = "allow"
