[package]
name = "cue-core"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
thiserror.workspace = true
anyhow.workspace = true
dirs.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
tracing.workspace = true
tracing-appender.workspace = true
tracing-subscriber.workspace = true
sha2 = "0.10"

[lints.clippy]
derivable_impls = "allow"
large_enum_variant = "allow"
should_implement_trait = "allow"
