[package]
name = "cue-llm"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
uuid = { version = "1", features = ["v4"] }
cue-cloud-client = { path = "../cue-cloud-client" }
async-trait.workspace = true
futures-util.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
obfstr.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
wiremock.workspace = true
